name: Docker Image CI

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag otohits-image:$(date +%s)
